---
name: Code Analysis

# 触发条件：在 PR 请求到 'main' 分支时运行
"on":
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      # 检查敏感信息
      - name: Install git-secrets
        run: |
          git clone https://github.com/awslabs/git-secrets.git
          sudo make install -C git-secrets
          git secrets --install
          git secrets --scan

      - name: Set up Flutter
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build libgtk-3-dev pkg-config libx11-dev binutils libgl1-mesa-dev libayatana-appindicator3-dev
          mkdir -p $HOME/flutter
          curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.2-stable.tar.xz
          tar xf flutter_linux_3.22.2-stable.tar.xz -C $HOME/flutter --strip-components=1
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          export PATH="$HOME/flutter/bin:$PATH"
          flutter --version
          flutter doctor

      # 运行 Flutter 的静态分析
      - name: Run flutter analyze
        run: |
          flutter analyze
